### ISSUE TITLE
[bug] Flutter 3.0 padding text down

### ISSUE THREAD

**Issue by RoyalCoder88** [bdlukaa/rounded_background_text#1]
Hi friends,

Thanks for your great package I got an issue after upgrading to flutter 3.0, the text floating down from the background :( can you please help me fix this issue? Thanks in advance!

My widget:
` Positioned(
                                      left: 15,
                                      top: 10,
                                      child: Container(
                                        alignment: Alignment.center,
                                        //decoration: ,
                                        width: 150,
                                        height: 40,
                                        color: Colors.transparent,
                                        child: RoundedBackgroundText(
                                          'TEXT ' ,
                                          style: const TextStyle(
                                              fontSize: 16,
                                              fontWeight: FontWeight.w900),
                                          backgroundColor: Colors.orangeAccent
                                              .withOpacity(0.9),
                                          textAlign: TextAlign.center,
                                          maxLines: 1,
                                          innerRadius: 1.0,
                                          outerRadius: 6.0,
                                          // textHeightBehavior:
                                          //     const TextHeightBehavior(
                                          //   applyHeightToFirstAscent: false,
                                          //   applyHeightToLastDescent: false,
                                          //   leadingDistribution:
                                          //       TextLeadingDistribution
                                          //           .even,
                                          // ),
                                        ),`

![Screenshot 2022-05-13 145414](https://user-images.githubusercontent.com/6507433/168300306-de11fadd-11e7-4d8d-af00-bc05be99d2ed.png)

**Comment by bdlukaa** [comment]
https://github.com/flutter/flutter/issues/104153

**Comment by bdlukaa** [comment]
According to https://github.com/flutter/flutter/issues/104153#issuecomment-1198567691, this issue has been fixed on the Flutter master branch

**Comment by bdlukaa** [comment]
Closing this as resolved! It is working on the Flutter master channel

![example 29_07_2022 21_58_41](https://user-images.githubusercontent.com/45696119/181864151-3ffe94d5-1bf8-4583-aacc-0630161cdd7b.png)
