### ISSUE TITLE
Placing the widget

### ISSUE THREAD

**Issue by polarby** [bdlukaa/rounded_background_text#11]
**Describe the bug**
I am kind of puzzled how the new version was able to get released. I see no option to handle this widget as before.
And I also seem to use a specific size as a parent, which is a kind of contra-production if the goal is to have a dynamic size text field?!

**To Reproduce**
Run the code below and try to center the widget.
(Keeps being stuck at the top-left corner)
```
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Center(
      child: RoundedBackgroundTextField(
        autofocus: true,
        keyboardType: TextInputType.multiline,
        enableInteractiveSelection: true,
        controller: controller,
      ),
    );
  }
```

**Expected behavior**
Being able to move and handle the widget like the normal Text() widget or any other normal widget.

I am now using version [0.1.3](https://pub.dev/packages/rounded_background_text/versions/0.1.3) because every newer one is not functional at all. Please fix

**Comment by bdlukaa** [comment]
The text field is aligned with the background with the TextAlign property (see https://github.com/bdlukaa/rounded_background_text/blob/main/lib/src/rounded_background_text_field.dart#L417-L429).

It takes all the available space, so if you want to size the text field, you can wrap it in a SizedBox. Since now the text field can be scrollable, with no autoresize, it makes sense to have it aligned on the top left because of the limitations of using a CustomPainter.

But leaving this as a valid request because I would also like to have the text in the TextField at the center

**Comment by polarby** [comment]
Any update on this? Using Sized Box is not an option for me as I want dynamic resizing when typing.

**Comment by bdlukaa** [comment]
Unfortunately, the `RoundedBackgroundText` depends on the constraints the parent gives to it. To counterpart this issue, using a render object would be the appropriate solution, but I unfortunately don't have time to invest on this.

A workaround to your issue can be dynamically updating the size of the `SizedBox` based on the content of the text field.

**Comment by polarby** [comment]
That would be an option for me, but am unaware of how to get the current number of lines & height of a line, as this is controlled by your package no? 
I have only the constraint size of the rounded background. How calculate the amount of lines (wrappings) of this text widget?

**Comment by bdlukaa** [comment]
If you have access to the text controller, you can do the following to get the line metrics:

```dart
final span = textControler.buildTextSpan(context: context, style: style);
span.layout(maxWidth: maxWidth);

final lines = span.computeLineMetrics();
```

But you still need to provide a max width :/

**Comment by polarby** [comment]
Thanks a lot! I was finally able to solve it! Couldn't reproduce your code. But this worked for me, which focuses the text in the center (same as the hint text):

```dart

 final span = textControler.buildTextSpan(context: context, style: textStyle, withComposing: true);
 final TextPainter textPainter = TextPainter(text: span, maxLines: 5, textDirection: TextDirection.ltr);
 textPainter.layout(maxWidth: maxTextWidth);
 
 return Container(
      padding: EdgeInsets.only(top: (textPainter.width > 0 ? 1 : 0) * (widget.size.height / 2 - textPainter.height / 2)),
      child: ...
```
PS. I would like to buy you a coffee, do you mind adding a button to the repository (Patreon is too expensive to me)
