### ISSUE TITLE
Text is outside its background

### ISSUE THREAD

**Issue by arnirichard** [bdlukaa/rounded_background_text#13]
**Describe the bug**
When using Thai characters, sometimes the text appears partly outside its background.
Tested both on Android and web

Is there any workaround?

**To Reproduce**
1. Add text 
`RoundedBackgroundText('ที่',
    style: TextStyle(fontFamily: 'Sarabun', fontSize: 26),
    backgroundColor: Colors.amber)`
2. Add font (fonts folder is attached) 
pubspec..yaml:
`  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf`

**Expected behavior**
Text should appear inside its background

**Screenshots**
![image](https://user-images.githubusercontent.com/95013472/184574975-0e3afc0d-98c3-4de8-89a7-0e18a4744b35.png)

**Additional context**
Fonts folder:
https://www.arnirichard.dk/fonts.zip

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.1.0-0.0.pre.2268, on Microsoft Windows [Version 10.0.22000.856], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by bdlukaa** [comment]
The same happens with Korean, Japanese, Chinese, Hebrew and Arabic alphabets. It seems flutter fails to correctly calculate the height of the line for those alphabets.

Related:
  * https://github.com/flutter/flutter/issues/39755
  * https://github.com/flutter/flutter/issues/30940

By reading some threads, it may be related to the specific font used

**Comment by bdlukaa** [comment]
This issue seems to have been fixed by the flutter team:

thai: 
![thai](https://github.com/bdlukaa/rounded_background_text/assets/45696119/6bd8a873-f1bf-4881-af61-bda61d7ac6f5)

korean: 
![korean](https://github.com/bdlukaa/rounded_background_text/assets/45696119/ee2a2dd8-ff94-4b70-b482-a3760749b6f9)

japanese:
![japanese](https://github.com/bdlukaa/rounded_background_text/assets/45696119/a1fd09b1-d4d6-4065-b344-7e7aeefac2c1)
