### ISSUE TITLE
crashes with just_the_tooltip

### ISSUE THREAD

**Issue by sgehrman** [bdlukaa/rounded_background_text#14]
I didn't look into this closely, but it didn't work.

The following assertion was thrown building
js_primitives.dart:30 _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#1c2cf](dirty, state:
js_primitives.dart:30 _OverlayEntryWidgetState#d6b7f):
js_primitives.dart:30 The _RenderLayoutBuilder class does not support dry layout.
js_primitives.dart:30 Calculating the dry layout would require running the layout callback speculatively, which might
js_primitives.dart:30 mutate the live render object tree.

**Comment by bdlukaa** [comment]
You must provide bounds to the text widget. It can not render on an unbounded box.
