### ISSUE TITLE
How to calculate it's width or height with a LayoutBuilder?

### ISSUE THREAD

**Issue by linslouis** [bdlukaa/rounded_background_text#15]
**Is your feature request related to a problem? Please describe.**
 I am trying to place this widget in a positioned widget.And i want to set the 'left:' parameter to screenWidth - RoundedBackgroundText.width
**Describe the solution you'd like**
I there is a size parameter available then it would be easy for me to position this widget where i wanted.

 
**Additional context**
Is there any other way to  accomplish my requirement with current version?

**Comment by bdlukaa** [comment]
A `LayoutBuilder` is only used to determine the available space the widget can take. The size is determined by the parent. You may be looking for a `GlobalKey`, where you can find the widget render box and get size from there (See [this](https://stackoverflow.com/a/75449790/11622876))
