### ISSUE TITLE
[bug] Vertical Alignment Issue

### ISSUE THREAD

**Issue by hm21** [bdlukaa/rounded_background_text#19]
**Describe the bug**
The bug I've encountered is that the text within the painted content is not vertically aligned to the center.

**To Reproduce**
Create a widget with a large font size like below. Then use the Flutter Widget Inspector and tap on the text. This way you can see it clearly.
```dart
@override
Widget build(BuildContext context) {
   return Scaffold(
      backgroundColor: Colors.blueGrey.shade500,
      body: Center(
        child: RoundedBackgroundText(
          'Hello World',
          backgroundColor: Colors.white,
          style: const TextStyle(fontSize: 48),
        ),
      ),
    );
}
```

**Expected behavior**
I expected the text inside the painted content to be vertically aligned at the center.

**Screenshots**
![Screenshot_20231229_140736](https://github.com/bdlukaa/rounded_background_text/assets/40503456/946d9a52-aaa7-4e1f-8bf8-809d37ad5a44) 

**Additional context**
I think a potential improvement is to update the y-position for the first line. However, I'm not sure if this is the optimal approach.

```dart
double get y {
    final y = metrics.baseline - metrics.ascent;
    if (isFirst) {
      // Replace => return y;
      return (height - metrics.height -_lastLinePadding.bottom)/2;
    } else if (isLast) {
      return y + (_lastLinePadding.top / 2);
    } else {
      return y - _innerLinePadding.top;
    }
  }
```

**Comment by bdlukaa** [comment]
If there is only one line, a RRect is directly rendered behind the text (https://github.com/bdlukaa/rounded_background_text/blob/main/lib/src/rounded_background_text.dart#L356-L371). In the `y`, we should check if the line is the only line.

**Comment by hm21** [comment]
I've taken a closer look at your code, and it seems like a small offset adjustment could help center the text better. By using half of the `_lastLinePadding.bottom` as the offset, we achieve a more centered appearance.

Here's the modified code:

```Dart
 @override
  void paint(Canvas canvas, Size size) {
    final lineInfos = computeLines(text);

    for (final lineInfo in lineInfos) {
      paintBackground(canvas, lineInfo);
    }
    final metrics = lineInfos.last.last.metrics;

    // Change offset.y to the same like the half of _lastLinePadding.bottom
    text.paint(canvas, Offset(0, metrics.height * 0.175 / 2));
  }
```
I've conducted some tests, and it appears that this adjustment results in a more centered text, as shown in the comparison images below:

**Before:**
<img src="https://github.com/bdlukaa/rounded_background_text/assets/40503456/ba94ec44-ecfa-4806-a734-f3c3bd8fd91b" alt="Before" width="400" height="300">

**After:**
<img src="https://github.com/bdlukaa/rounded_background_text/assets/40503456/42340f14-e9ed-4747-9843-d637dec48ff1" alt="After" width="400" height="300">

**Comment by bdlukaa** [comment]
While your solution is good, it breaks the text field. The actual text needs to be painted as if it were a `Text` widget, or, perhaps, an `EditableText`. Though, by changing the `bottom` of the first, inner, and last line paddings to the value suggested seems to have the same output:

```dart
  late final EdgeInsets _firstLinePadding = EdgeInsets.only(
    left: height * _horizontalPaddingFactor,
    right: height * _horizontalPaddingFactor,
    top: height * 0.3,
    bottom: height * 0.175 / 2,
  );
  late final EdgeInsets _innerLinePadding = EdgeInsets.only(
    left: height * _horizontalPaddingFactor,
    right: height * _horizontalPaddingFactor,
    top: 0.0,
    bottom: height * 0.175 / 2,
  );
  late final EdgeInsets _lastLinePadding = EdgeInsets.only(
    left: height * _horizontalPaddingFactor,
    right: height * _horizontalPaddingFactor,
    top: 0.0,
    bottom: height * 0.175 / 2,
  );
```

**Comment by bdlukaa** [comment]
Can you try #20 and see the result? I'd love your feedback on this

**Comment by hm21** [comment]
Great job! I tested it and it works as expected. Below you can see the image from my tests, and it is now vertically centered. Thanks for the fast solution.

<img src="https://github.com/bdlukaa/rounded_background_text/assets/40503456/6ef2041c-b077-4713-8b48-049e3e568fb9" width="300">

**Comment by hm21** [comment]
Great job! I have tested it extensively, and it seems to work very well. 

But FYI, in my testing, I found that there is a problem with the selectable text. It seems that the text does not have the same line height and letter spacing as the selectable text. Below is an image where you can see the problem. I also saw in your web example that this problem already exists. However, I will close this issue because the vertical alignment is fixed with your solution. 
Maybe you already have a solution for the selectable text, but if not, it would make sense to open a `new issue`. Actually, I don't need this function but if I see you open a new issue for this and I have time, I can help to find a solution.

![image](https://github.com/bdlukaa/rounded_background_text/assets/40503456/22b9fc75-a925-4ec5-948c-1dfaa9a5d2b1)

**Comment by bdlukaa** [comment]
Thank you for your feedback! I published a new version with the fix.

I would love a new issue for `SelectableText`. As a workaround, one can use `RoundedBackgroundTextField` with `readOnly: true` to achieve a similar effect.
