### ISSUE TITLE
Space doesn't get background

### ISSUE THREAD

**Issue by polarby** [bdlukaa/rounded_background_text#2]
**Describe the bug**
When typing a space (`" "`) a background doesn't get added. When breaking the line twice and then typing again, you can create ONE single text element with TWO different backgrounds. This isn't very confusing for the user when he suddenly drags two elements while expecting to drag only one.

**To Reproduce**
1. Create a `RoundedBackgroundTextField` (make sure to set ` keyboardType: TextInputType.multiline,`)
2. Type "First line\n\nThird line"
3. See empty row

**Expected behavior**
Generally having the space character  (`" "`) rendered. 

**Screenshots**
![WhatsApp Image 2022-07-24 at 10 23 57 PM](https://user-images.githubusercontent.com/52090518/180704713-3b10bb04-192e-447c-8070-36b48103c18a.jpeg)

**Comment by bdlukaa** [comment]
That's the expected behavior. Empty lines aren't rendered
