### ISSUE TITLE
[bug] After executing flutter pub add rounded_background_text, an error occurred.

### ISSUE THREAD

**Issue by giantss** [bdlukaa/rounded_background_text#23]
<img width="1325" alt="image" src="https://github.com/bdlukaa/rounded_background_text/assets/13778798/f0109ccd-64e5-4aa8-bd87-cc533a519382">

**Comment by bdlukaa** [comment]
You need to use the latest flutter version.

**Comment by giantss** [comment]
Well, my environment is Flutter 3.10.5. I returned the rounded_background_text version to ^0.4.1 and no more errors were reported.
