### ISSUE TITLE
Hint doesn't work

### ISSUE THREAD

**Issue by polarby** [bdlukaa/rounded_background_text#3]
**Describe the bug**
The hint parameter is not built.

**To Reproduce**
1. Create Widget `RoundedBackgroundTextField`
2. add `hint: "text"`

**Expected behavior**
A lighter-colored placeholder hint that appears on the first line of the text field when the text entry is empty.

**Comment by martinmelchior** [comment]
Hello
Same error with 
  - Flutter 3.0.5 
  - rounded_background_text: ^0.1.3

![image](https://user-images.githubusercontent.com/64325299/181824966-e469324a-7af9-4a81-aa20-2136dd743e15.png)

![image](https://user-images.githubusercontent.com/64325299/181825160-2687a081-9a11-42f8-aed4-74046fa668df.png)

thx
