### ISSUE TITLE
Auto-Resize of text has no background 

### ISSUE THREAD

**Issue by polarby** [bdlukaa/rounded_background_text#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**
N/A

**Screenshots**

<img src="https://user-images.githubusercontent.com/52090518/182006219-ecdd54b0-26d7-4f0a-9dc3-490145a75f44.jpeg" width="200">

**Additional context**
N/A

**Comment by bdlukaa** [comment]
Would #4 fix this issue?

**Comment by polarby** [comment]
Probably not. The bug here is either the wrong padding of the different lines or it is the scaling of the font. I don't see a reason why a scrollable function could solve this. I will check again when #4 is done.
