### ISSUE TITLE
Disable auto-resize of text

### ISSUE THREAD

**Issue by polarby** [bdlukaa/rounded_background_text#8]
**Is your feature request related to a problem? Please describe.**
I have an application that does not need the option to resize the font size when typing. I have an extra option for the user to do this. 

**Describe the solution you'd like**
I would love to have a parameter, where I simply can disable this feature. Like `autoResize: false`. In the best case, it simply prohibits adding more in the text field, when the max limit is reached. 

**Describe alternatives you've considered**
 Alternatively, I could also imagine something like in the `Text` widget, where there is a parameter for overflow (`overflow: TextOverflow.fade`).

**Additional context**
This is a fundamental problem, that needs to be solved. The usage of this plugin is otherwise critical or not possible.

**Comment by bdlukaa** [comment]
Would #4 fix your issue?

**Comment by polarby** [comment]
Maybe. Would there also be the option to disable the scroll physics at some controller or something? Like `pysics: NeverScrollableScrollPhysics()`? So it would simply keep typing, without being able to scroll down. Is it understandable what i am saying?

**Comment by bdlukaa** [comment]
Yes, it'd be possible to use a custom physics. See #5

**Comment by bdlukaa** [comment]
Can this be closed?

**Comment by polarby** [comment]
I could test it yet, because of the difficulties with positioning. I am gonna close it for now and will open it up in case there are errors.
